### ISSUE TITLE
Upgrade kill() function

### ISSUE THREAD

**Issue by ZeroVash** [naveed92/dm-ocg-octgn#21]
Function needs an upgrade to allow filtering for parameters. Ex: Untapped, Race, Civilization, Etc.

**Comment by naveed92** [comment]
Kill function now filters tapped and untapped, this should cover Death Smoke, Death Chaser and Phantasm Clutch

**Comment by naveed92** [comment]
kill function now filters for civilization as well, and can be used to target own creatures when needed. Race filter seems unnecessary for now, but will be added when necessary
