### ISSUE TITLE
Deck search shouldn't be filtered technically

### ISSUE THREAD

**Issue by naveed92** [naveed92/dm-ocg-octgn#23]
Cards that let you search deck should allow you to see the entire deck, even if they contain cards you normally wouldn't be able to take out. e.g (via Evolution Totem). This is usually done to determine which cards are in shields.

**Comment by ZeroVash** [comment]
Ah right. That's true. Then some updates have to be made to the search
function.
It's not really much. It can show the entire deck, but only allow cards to be taken that match the criteria.
I'll work on this ASAP:

**Comment by ZeroVash** [comment]
I'll work ASAP:

**Comment by ZeroVash** [comment]
Fixed.
