### ISSUE TITLE
search and fromMana functions do not notify the opponent which cards were taken

### ISSUE THREAD

**Issue by naveed92** [naveed92/dm-ocg-octgn#27]
Seems both call the toHand function, and that doesn't notify properly.

**Comment by manveersk** [comment]
For instance Belix calls fromMana
In the definition of fromMana, it's written
def fromMana(count = 1, TypeFilter = "ALL", CivFilter = "ALL", RaceFilter = "ALL", show = False, toGrave = False)

BUT, the toHand requires show to be set to TRUE
	if show == True: 
		notify("{} moves {} to hand from {}.".format(card.owner, card, src.name))
	else:
		whisper("moved {} to hand from {}.".format(card, src.name))

so maybe change show to True as default value? Or maybe pass True?

**Comment by ZeroVash** [comment]
It's closed but no answer was given :) Might be useful for the future to know what changed.

**Comment by naveed92** [comment]
I'm pretty sure changing card to card.name did the trick
