### ISSUE TITLE
Aqua Deformer - Partially Automated

### ISSUE THREAD

**Issue by ZeroVash** [naveed92/dm-ocg-octgn#7]
![aquadeformer](https://cloud.githubusercontent.com/assets/1907476/8568959/bb2c2658-256a-11e5-976a-8e7274538d20.jpg)

As it stands, only the first part of the effect is done. Needs a way to make the opp choose his two cards.

**Comment by naveed92** [comment]
Remotecalls to the opponent using the fromMana() function?

**Comment by ZeroVash** [comment]
How do you define the player to apply the effect for? 
remotecall(not me , ...) doesn't seem to work,

**Comment by naveed92** [comment]
players[1] might be an alternative. Though im not sure how to implement it for 4-player games

**Comment by naveed92** [comment]
or present the caster with a choice showing a list of all players in the game. pass a remotecall to the selected player

**Comment by naveed92** [comment]
Player Targetting will be implemented soon in OCTGN. That should make it easier to automate stuff like this, especially in the context of 3-way or 4-way games.

Currently a possible workaround would be for the player to target any card in the opponent's manazone before summoning deformer, then using card.owner of the targetted card to pass the remotecall.

**Comment by ZeroVash** [comment]
So, do we wait for player targeting? I suppose a label can be added to say that we are waiting for an OCTGN update.

**Comment by brine** [comment]
you could also use the askChoice dialog API and pass a list of players.  Just make sure you include something to remove yourself from the list (if you're dealing with opponents), and a dictionary linking return indeces to player IDs

**Comment by manveersk** [comment]
I've also been trying to figure out how to this, since I wanted to automate Soulswap.

**Comment by ZeroVash** [comment]
Effect is fixed on this card and on Shtra on my next push.
