### ISSUE TITLE
Artisan Picora - Wrongly Automated

### ISSUE THREAD

**Issue by ZeroVash** [naveed92/dm-ocg-octgn#8]
![artisanpicora](https://cloud.githubusercontent.com/assets/1907476/8568988/f500ce1a-256a-11e5-980b-dd0a04bae654.jpg)

Artisan Picora sends card to hand instead of sending it to the graveyard.

**Comment by naveed92** [comment]
hmm, i see it's coded properly, have to test myself

**Comment by ZeroVash** [comment]
Didn't realize i had fixed it xD The comments were before the last fixes D: 
So yeah this can be closed after someone tests it to be sure.

**Comment by naveed92** [comment]
Works fine.
